# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deploychain < Formula
  desc "Simple app to demonstrate deployment chain"
  homepage "https://www.andre.sk"
  version "0.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://s3.andre.sk/deploychain/deploychain/0.0.2/deploychain_0.0.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "5e1933e7f6f38fb35f6d587f76c91abf4c2b12f06a85864c1fe2d106070dca86"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://s3.andre.sk/deploychain/deploychain/0.0.2/deploychain_0.0.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "9e63f69f5a8c7b2bc23ba3c2d6b65bd0f9d7973ca9c10676ef71172b9ff1683a"
  end

  def install
    bin.install "deploychain"
  end

  test do
    system "#{bin}/program --version"
  end
end
