# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deploychain < Formula
  desc "Simple app to demonstrate deployment chain"
  homepage "https://www.andre.sk"
  version "0.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://s3.andre.sk/deploychain/deploychain/0.0.2/deploychain_0.0.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "dc99e355abfeab187f5623236ced1ae7e0d148800ca6ba7608ba7efb31ef0026"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://s3.andre.sk/deploychain/deploychain/0.0.2/deploychain_0.0.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "dff1c1ec9e1b7e89efb0cf897f973caf3f1e171a28fd943a89f9a8b5cca6a2e3"
  end

  def install
    bin.install "deploychain"
  end

  test do
    system "#{bin}/program --version"
  end
end
