# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mailparser < Formula
  desc "Parse incoming email"
  homepage "https://www.andre.sk"
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://go-mailparser.s3.amazonaws.com/v0.0.3/mailparser_0.0.3_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "0257c2e8b85cc9d599b03731b1244b9622422b610d8a098e2ed684803356b904"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://go-mailparser.s3.amazonaws.com/v0.0.3/mailparser_0.0.3_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "e41a50421f35b9e758274811571b790ac23340ae93fae10bcfa42c49f57b3154"
  end

  def install
    bin.install "mailparser"
    etc.install "configs/mailparser.conf"
  end

  test do
    system "#{bin}/program --version"
  end
end
