# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdfmanip < Formula
  desc "Tool to manipulate PDF files in archive"
  homepage "https://www.andre.sk"
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://go-pdfmanip.s3.amazonaws.com/v0.0.6/pdfmanip_0.0.6_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "aa05fbef41e68515be737060d39363447668616354ef2172f75b44f39d22edcc"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://go-pdfmanip.s3.amazonaws.com/v0.0.6/pdfmanip_0.0.6_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "a1a67b42dac31b2ffedee7a832420c83bedd0239ced890bb424173f565898ce8"
  end

  def install
    bin.install "pdfmanip"
    man1.install "_output/pdfmanip.1.gz"
    etc.install "configs/pdfmanip.conf"
  end

  test do
    system "#{bin}/program --version"
  end
end
