# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdfmanip < Formula
  desc "Tool to manipulate PDF files in archive"
  homepage "https://www.andre.sk"
  version "0.0.7"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://go-pdfmanip.s3.amazonaws.com/v0.0.7/pdfmanip_0.0.7_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "54f8a5e5a7d5443f32f2fda9a63d481b35d77d87a773cfa3c78d7c9d7f423af8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://go-pdfmanip.s3.amazonaws.com/v0.0.7/pdfmanip_0.0.7_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "512ef6438da8fde4befdbd268772ebbe1408162713bdbe0e08487f36b8e6fdcc"
  end

  def install
    bin.install "pdfmanip"
    man1.install "_output/pdfmanip.1.gz"
    etc.install "configs/pdfmanip.conf"
  end

  test do
    system "#{bin}/program --version"
  end
end
