# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdfmanip < Formula
  desc "Tool to manipulate PDF files in archive"
  homepage "https://www.andre.sk"
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://go-pdfmanip.s3.amazonaws.com/v0.0.6/pdfmanip_0.0.6_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "63ab644d18830b8fed5a1b9d3371013bc67b8c551f418651e48fb03c1c9a992d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://go-pdfmanip.s3.amazonaws.com/v0.0.6/pdfmanip_0.0.6_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "50b3da294c7367bc5c53979899371c6e1ec0a9d161989ca83402d5e3327eb9d4"
  end

  def install
    bin.install "pdfmanip"
    man1.install "_output/pdfmanip.1.gz"
    etc.install "configs/pdfmanip.conf"
  end

  test do
    system "#{bin}/program --version"
  end
end
